project:
  type: book
  output-dir: docs
  resources:
    - data/* # Include all files

book:
  title: "R for Data Science (2e)"
  description: |
     🖥️ Interactive Version with <a href="https://github.com/coatless/quarto-webr">quarto-webr</a>
     by <a href="https://fralfaro.github.io/portfolio/">Francisco Alfaro</a>
  reader-mode: true
  author: "Hadley Wickham, Mine Çetinkaya-Rundel, Garrett Grolemund"
  date: "07/11/2023"
  page-footer:
    left: |
      R for Data Science (2e) was written by Hadley Wickham, <br> Mine
      Çetinkaya-Rundel, and Garrett Grolemund.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.jpg
  favicon: cover.jpg
  site-url: https://r4ds.hadley.nz/
  repo-url: https://github.com/hadley/r4ds/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd

    - preface-2e.qmd
    - intro.qmd

    - part: whole-game.qmd
      chapters:
        - data-visualize.qmd
        - workflow-basics.qmd
        - data-transform.qmd
        - workflow-style.qmd
        - data-tidy.qmd
        - workflow-scripts.qmd
        - data-import.qmd
        - workflow-help.qmd

    - part: visualize.qmd
      chapters:
        - layers.qmd
        - EDA.qmd
        - communication.qmd

    - part: transform.qmd
      chapters:
        - logicals.qmd
        - numbers.qmd
        - strings.qmd
        - regexps.qmd
        - factors.qmd
        - datetimes.qmd
        - missing-values.qmd
        - joins.qmd

    - part: import.qmd
      chapters:
        - spreadsheets.qmd
        - databases.qmd
        - arrow.qmd
        - rectangling.qmd
        - webscraping.qmd

    - part: program.qmd
      chapters:
        - functions.qmd
        - iteration.qmd
        - base-R.qmd

    - part: communicate.qmd
      chapters:
        - quarto.qmd
        - quarto-formats.qmd

format:
  html:
    theme:
      light: [ flatly, r4ds/custom2.scss ]
      dark: [ flatly, r4ds/custom2.scss, stylesheets/theme-dark.scss ]
    code-link: true

    author-meta: "Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund"
    include-in-header: "plausible.html"
    callout-appearance: simple



editor: visual

filters:
  - webr

